name: Report an issue with @pattern-ui/ scoped package
description: Tell us if something is not working as expected
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        ## Thanks for reaching out!
        Before submitting an issue please make sure that you use latest version of all @pattern-ui/ packages.
  - type: dropdown
    id: version
    attributes:
      label: What package has an issue
      options:
        - '@pattern-ui/core'
        - '@pattern-ui/dates'
        - '@pattern-ui/hooks'
        - '@pattern-ui/form'
        - '@pattern-ui/notifications'
        - '@pattern-ui/rte'
        - '@pattern-ui/prism'
        - '@pattern-ui/modals'
        - '@pattern-ui/dropzone'
        - '@pattern-ui/spotlight'
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: In which browser did the problem occur
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: If possible, please include a link to a codesandbox with the reproduced problem
      description: Codesandbox template – https://codesandbox.io/s/pattern-template-9ze89
  - type: dropdown
    id: fix
    attributes:
      label: Do you know how to fix the issue
      options:
        - 'Yes'
        - 'No'
  - type: dropdown
    id: participate
    attributes:
      label: Are you willing to participate in fixing this issue and create a pull request with the fix
      options:
        - 'Yes'
        - 'No'
  - type: textarea
    id: possibleFix
    attributes:
      label: Possible fix
