export { default as icons } from './Tabs.icons.demo';
export { default as colors } from './Tabs.colors.demo';
export { configurator } from './Tabs.configurator.demo';
export { positionConfigurator } from './Tabs.positionConfigurator.demo';
export { default as stylesApi } from './Tabs.stylesApi.demo';
export { default as pull } from './Tabs.pull.demo';
export { default as disabled } from './Tabs.disabled.demo';
export { default as unstyled } from './Tabs.unstyled.demo';
export { default as rightSection } from './Tabs.rightSection.demo';
export { default as deactivate } from './Tabs.deactivate.demo';
export { default as keyboardActivation } from './Tabs.keyboardActivation.demo';
export { default as inverted } from './Tabs.inverted.demo';
